### ISSUE TITLE
Probe_Hole 

### ISSUE THREAD

**Issue by ryanjblajda** [crpalmer/shapeoko#1]
im sure its something to do with gSender, but trying to run the Probe_Hole macro fails, giving

"bad number format" errors.

**Comment by crpalmer** [comment]
When you insert a tool, you need to run the macro Probe_Tool.

When you insert the probe, you need to run the macro Probe_Insert_Probe.

These define various global variables, most notably the fast and slow probe speeds.  When you load a tool, it assumes you have some kind of inductive probe and sets very slow probe speeds but when you load the probe it sets much higher probe speeds.

If you are just trying to use the Probe_Hole macro independent of my other macros, you'll need to define you own variables:

global.state.PROBE_DISTANCE
global.state.PROBE_FEED_FAST
global.state.PROBE_FEED_SLOW

If you have run Probe_Insert_Probe and are still getting an error, can you post the output of the console when you run the probing?

**Comment by crpalmer** [comment]
According the Carbide Community forum, you figured out the missing variables.

**Comment by ryanjblajda** [comment]
I did figure that out. thanks for the quick response!
